---
- hosts: v112
  remote_user: ubuntu
  tasks:
  - name: upload ssh key                
    authorized_key:
      user: ubuntu
      state: present
      manage_dir: yes
      key: https://github.com/englert.keys